### ISSUE TITLE
Unable to re-register device after deleting PI Device registration from Dashboard

### ISSUE THREAD

**Issue by jaalger** [presence-insights/pi-clientsdk-ios#18]
Removing a device registration from the PI Dashboard does not allow me to re-register the device from client side. When I attempt to re-register the device I get the following error:

![image](https://cloud.githubusercontent.com/assets/4974364/12989324/06871720-d0d3-11e5-8c3c-3a495b29fba6.png)

The device registration is no longer visible in the PI Dashboard and I can not register the device anymore. I have to remove the registration using swagger in order to successfully register.

**Comment by CiaranHannigan** [comment]
Found the bug. registerDevice had the logic to handle when a device document already exists, but performRequest was treating all 400 errors the same and did not pass along the response, just the error.

https://github.com/presence-insights/pi-clientsdk-ios/pull/21
