### ISSUE TITLE
Prefix core location beacon region identifier with com.ibm.pi

### ISSUE THREAD

**Issue by lizeray** [presence-insights/pi-clientsdk-ios#27]
the current implementation is fragile, it assumes that all beacon regions are managed by the SDK. if the core location region identifiers were prefixed with com.ibm.pi, it would be more robust

**Comment by CiaranHannigan** [comment]
https://github.com/presence-insights/pi-clientsdk-ios/pull/41

**Comment by CiaranHannigan** [comment]
Great recommendation :smile:
