### ISSUE TITLE
Background Mode

### ISSUE THREAD

**Issue by robpuryear** [presence-insights/pi-clientsdk-ios#36]
The locationManager sets the property allowsBackgroundLocationUpdates to true in the SDK which requires Background Modes to be turned on for location. Apple is very strict with approving apps with Background Modes turned on. As long as the locationManager has requestAlwaysAuthorization() = true (which the SDK turns on), the locationManager will get the device location in the background and also when the app isn’t running.

**Comment by lizeray** [comment]
duplicate: https://github.com/presence-insights/pi-clientsdk-ios/issues/30#issuecomment-202890317
